# Generated by Django 3.2.6 on 2021-09-02 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app', '0002_auto_20210902_2315'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('username', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=20)),
                ('status', models.CharField(default='', max_length=10)),
            ],
            options={
                'db_table': 'UserInfo',
            },
        ),
    ]
