# Generated by Django 3.2.6 on 2021-09-03 02:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AdminApp', '0001_initial'),
        ('app', '0003_userinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyCart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.IntegerField()),
                ('eleproduct', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='AdminApp.electronicsproduct')),
                ('fashionproduct', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='AdminApp.fashionproduct')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.userinfo')),
            ],
            options={
                'db_table': 'MyCart',
            },
        ),
    ]
