# Generated by Django 3.2.6 on 2021-09-03 03:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AdminApp', '0001_initial'),
        ('app', '0004_mycart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mycart',
            name='eleproduct',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='AdminApp.electronicsproduct'),
        ),
        migrations.AlterField(
            model_name='mycart',
            name='fashionproduct',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='AdminApp.fashionproduct'),
        ),
    ]
