# Generated by Django 3.2.6 on 2021-09-04 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_profile_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_no', models.CharField(max_length=16)),
                ('cvv', models.CharField(max_length=3)),
                ('expiry', models.CharField(max_length=7)),
                ('balance', models.FloatField(default=10000)),
            ],
            options={
                'db_table': 'Payment',
            },
        ),
    ]
