# Generated by Django 3.2.6 on 2021-09-06 07:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AdminApp', '0002_auto_20210905_1215'),
        ('app', '0011_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='BuyNow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.IntegerField()),
                ('price', models.FloatField(default=100)),
                ('eleproduct', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AdminApp.electronicsproduct')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.userinfo')),
            ],
            options={
                'db_table': 'BuyNow',
            },
        ),
    ]
