# Generated by Django 3.2.6 on 2021-09-13 03:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_buynow'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BuyNow',
        ),
    ]
