# Generated by Django 3.2.6 on 2021-09-02 17:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Electronics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ele_name', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'Electronics',
            },
        ),
        migrations.CreateModel(
            name='Fashion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fashion_name', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'Fashion',
            },
        ),
        migrations.CreateModel(
            name='FashionProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fashionproductname', models.CharField(max_length=20)),
                ('fashionproduct_image', models.ImageField(default='abc.jpg', upload_to='images')),
                ('price', models.FloatField(default=100)),
                ('description', models.CharField(max_length=10000)),
                ('fashion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AdminApp.fashion')),
            ],
            options={
                'db_table': 'FashionProduct',
            },
        ),
        migrations.CreateModel(
            name='ElectronicsProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('electronicsproductname', models.CharField(max_length=20)),
                ('electronicsproduct_image', models.ImageField(default='abc.jpg', upload_to='images')),
                ('price', models.FloatField(default=100)),
                ('description', models.CharField(max_length=10000)),
                ('electronics', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AdminApp.electronics')),
            ],
            options={
                'db_table': 'ElectronicsProduct',
            },
        ),
    ]
