# Generated by Django 3.2.6 on 2021-09-05 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='electronicsproduct',
            name='electronicsproductname',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='fashionproduct',
            name='fashionproductname',
            field=models.CharField(max_length=50),
        ),
    ]
